declare const _default: {
    CardanoBlockMetadataNotFound: string;
    CardanoClientFetchHttpCodeWithNetworkIssue: string;
    CardanoFileReaderBlockCannotReadDirectory: string;
    CardanoFileReaderBlockCannotReadFile: string;
    CardanoWalletIncorrectImportString: string;
    CardanoProcessorCannotProcessBlocksBeforeGenesis: string;
    CardanoProcessInvalidPreviousBlockHash: string;
    CardanoRawDataParserInvalidBlockData: string;
    CardanoRawDataParserInvalidMagicBytes: string;
    LockIdentifierIncorrectFormat: string;
    LockMonitorCurrentValueTimeLockInPendingState: string;
    LockMonitorDesiredLockAmountIsNotWholeNumber: string;
    LockMonitorNotEnoughBalanceForFirstLock: string;
    LockMonitorNotEnoughBalanceForRelock: string;
    LockMonitorTransactionFeesAmountIsNotWholeNumber: string;
    LockResolverDurationIsInvalid: string;
    LockResolverRedeemScriptIsInvalid: string;
    LockResolverRedeemScriptIsNotLock: string;
    LockResolverTransactionIsNotPayingToScript: string;
    LockResolverTransactionNotConfirmed: string;
    LockResolverTransactionNotFound: string;
    DatabaseDowngradeNotAllowed: string;
    ValueTimeLockInPendingState: string;
    VersionManagerVersionStringNotFound: string;
};
export default _default;
